[pytest]
pythonpath = .
markers =
    PositiveApi: positive API scenarios
    NegativeApi: negative API scenarios
    NegativeDashboard: negative dashboard permission scenarios
    sql: sqlite validation tests
    api: generic API tests
    ui: generic UI tests
    smoke: smoke tests
    regression: regression tests

addopts = -v -s --tb=short --durations=5 --color=yes

log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)8s] %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S
